name: build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - uses: actions/checkout@v4
      - run: go mod download
      - name: Build Windows
        env:
          GOOS: windows
        run: go build -v -o vider-downloader.exe
      - name: Build Linux
        env:
          GOOS: linux
        run: go build -v -o vider-downloader-linux
      - name: Build Mac
        env:
          GOOS: darwin
        run: go build -v -o vider-downloader-mac
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            vider-downloader.exe
            vider-downloader-linux
            vider-downloader-mac
